name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with: 
        toolset: 14.26
        arch: x86
    - run: |
        msbuild /p:Configuration=Release
        Release/GHAnalysis.exe
    - uses: actions/upload-artifact@v2
      with:
        name: GHAnalysis
        path: Release/GHAnalysis.exe
